name: ci

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

  # test:
  #   name: Unit Tests
  #   runs-on: ubuntu-latest
  #   needs: lint
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20.11.0

  #     - name: Install Chromium for headless tests
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y chromium-browser

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Run tests
  #       run: npm run test --watch=false --code-coverage --browsers=ChromeHeadless

  #     - name: Upload coverage report
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: coverage
  #         path: coverage

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

